import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { WarsFile, type War, type Battle } from "@/lib/schema";

/**
 * Loads `data/build/wars.json`, validating it against the WarsFile schema.
 *
 * The wars/battles dataset is generated by a separate build step and may not
 * exist in every environment (the file is git-ignored under `data/build`).
 * Callers should treat a `null` return as "no wars data available" and skip
 * rendering theatre regions and battle markers — the rest of the timeline
 * continues to function normally.
 */
const WARS_PATH = resolve(process.cwd(), "data/build/wars.json");

let cached: { wars: War[]; battles: Battle[] } | null = null;
let cacheLoaded = false;

export async function loadWars(): Promise<{ wars: War[]; battles: Battle[] } | null> {
  if (cacheLoaded) return cached;
  cacheLoaded = true;

  if (!existsSync(WARS_PATH)) {
    cached = null;
    return cached;
  }

  let raw: string;
  try {
    raw = await readFile(WARS_PATH, "utf8");
  } catch (err) {
    console.error("[holocron] wars.json failed to read", err);
    cached = null;
    return cached;
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    console.error("[holocron] wars.json failed to parse", err);
    cached = null;
    return cached;
  }

  const validated = WarsFile.safeParse(parsed);
  if (!validated.success) {
    console.error(
      "[holocron] wars.json failed schema validation",
      validated.error.issues.slice(0, 3)
    );
    cached = null;
    return cached;
  }

  cached = { wars: validated.data.wars, battles: validated.data.battles };
  return cached;
}
